---
title: "Logistic Regression NFL"
author: "Sophie Giacobbe"
date: "4/5/2023"
output: pdf_document
---

```{r}
library(readr)
library(dplyr)
library(ggplot2)
```

```{r}
kicks <- read_csv("NFLKicks2.csv")
kicks <- kicks[kicks$field_goal_result != "blocked",]
kicks <- kicks[kicks$game_seconds_remaining <= 60,]
kicks <- kicks[-1]
kicks[, c('home_team', 'away_team','quarter_seconds_remaining', 'half_seconds_remaining', 'play_type', 'field_goal_result', 'home_timeouts_remaining', 'away_timeouts_remaining', 'home_wp', 'away_wp', 'game_id', 'play_id', 'posteam_type', 'location', 'roof')] <- list(NULL)
```

```{r}
kicks$temp[is.na(kicks$temp)] <- 65
kicks$wind[is.na(kicks$wind)] <- 0
```

```{r}
set.seed(478)
tsize <- nrow(kicks)*0.7
sub <- sample(1:nrow(kicks), size = tsize)
train <- kicks[sub,]
test2 <- kicks[-sub,]
test <- test2[-test2$sp]
```

```{r}
table(kicks$sp)
#78% made
```

```{r}
kicks_timeout <- glm(sp ~ timeout, data = train, family = binomial)
#:(
ggplot()+ 
  geom_point(aes(predict(kicks_timeout, test), test2$sp))
```

```{r}
kicks_dtimeouts <- glm(sp ~ defteam_timeouts_remaining, data = train, family = binomial)
#:( this model sucks
ggplot()+
  geom_point(aes(predict(kicks_dtimeouts, test), test2$sp))
```

```{r}
#model of things that felt helpful to me
kicks_2 <- glm(sp ~ game_seconds_remaining + drive + defteam_timeouts_remaining + score_differential + no_score_prob + opp_fg_prob + wp, data = train, family = binomial)
#predict(kicks_2, test)
ggplot()+ 
  geom_point(aes(predict(kicks_2, test), test2$sp))
```

```{r}
kicks_3 <- glm(sp ~ no_score_prob + opp_fg_prob, data = train, family = binomial)
ggplot()+ 
  geom_point(aes(predict(kicks_3, test), test2$sp))
```

```{r}
kicks_pos <- glm(sp ~ posteam, data = train, family = binomial)
# BAL, BUF, DET, JAX, LV, NE
ggplot()+ 
  geom_point(aes(predict(kicks_pos, test), test2$sp))
```

```{r}
kicks_secs <- glm(sp ~ game_seconds_remaining, data = train, family = binomial)
ggplot()+ 
  geom_point(aes(predict(kicks_secs, test), test2$sp))
```

```{r}
#sometimes this works and sometimes it doesnt. i cannot understand why. I am literally not changing anything I dont know why it freaks out. 
#kicks_whole <- glm(sp ~ ., data = train, family = binomial)
#ggplot()+
  #geom_point(aes(predict(kicks_whole, test), test$sp))
```


